[package]
name = "cfmm-contracts"
version = "0.0.1"
edition = "2021"
registry = "fulmin-labs-registry"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

ethers = "0.13.0"
serde_json = "1.0.79"

