[package]
name = "cfmm-contracts"
version = "0.0.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

ethers = "0.17.*" 
serde_json = "1.0.79"

