/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IBook__factory } from "./IBook__factory";
export { IBookEvents__factory } from "./IBookEvents__factory";
