#![allow(clippy::all)]
//! This lib contains abigen! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub mod all_knowing_oracle;
pub mod all_knowing_oracle_test;
pub mod book_single_chain;
pub mod i_all_knowing_oracle_events;
pub mod i_book_single_chain_events;
