/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface BookSingleChainInterface extends utils.Interface {
  functions: {
    "disputeTrade(address,address,uint256,uint256,address,uint128)": FunctionFragment;
    "fillTrade(address,address,uint256,uint256,address,uint128,uint256)": FunctionFragment;
    "fillTradeWithUpdatedFee(address,address,uint256,uint256,address,uint128,uint256,address,uint256,bytes)": FunctionFragment;
    "filledAmount(bytes32)": FunctionFragment;
    "filledAtBlock(bytes32)": FunctionFragment;
    "filledBy(bytes32)": FunctionFragment;
    "maxFeePct()": FunctionFragment;
    "numberOfTrades()": FunctionFragment;
    "oracle()": FunctionFragment;
    "owner()": FunctionFragment;
    "requestTrade(address,address,uint256,uint256,address)": FunctionFragment;
    "safeBlockThreshold()": FunctionFragment;
    "setMaxFeePct(uint128)": FunctionFragment;
    "setOwner(address)": FunctionFragment;
    "setSafeBlockThreshold(uint256)": FunctionFragment;
    "settleTrade(address,address,uint256,uint256,address,uint128)": FunctionFragment;
    "updateFeeForTrade(address,bytes32,uint256,bytes)": FunctionFragment;
    "whitelistToken(address,bool)": FunctionFragment;
    "whitelistedTokens(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "disputeTrade"
      | "fillTrade"
      | "fillTradeWithUpdatedFee"
      | "filledAmount"
      | "filledAtBlock"
      | "filledBy"
      | "maxFeePct"
      | "numberOfTrades"
      | "oracle"
      | "owner"
      | "requestTrade"
      | "safeBlockThreshold"
      | "setMaxFeePct"
      | "setOwner"
      | "setSafeBlockThreshold"
      | "settleTrade"
      | "updateFeeForTrade"
      | "whitelistToken"
      | "whitelistedTokens"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "disputeTrade",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "fillTrade",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "fillTradeWithUpdatedFee",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "filledAmount",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "filledAtBlock",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "filledBy",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(functionFragment: "maxFeePct", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "numberOfTrades",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "oracle", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "requestTrade",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "safeBlockThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxFeePct",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setOwner",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setSafeBlockThreshold",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "settleTrade",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "updateFeeForTrade",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistToken",
    values: [PromiseOrValue<string>, PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistedTokens",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "disputeTrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fillTrade", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fillTradeWithUpdatedFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "filledAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "filledAtBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "filledBy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "maxFeePct", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "numberOfTrades",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "oracle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requestTrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeBlockThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxFeePct",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setOwner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setSafeBlockThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settleTrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateFeeForTrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "whitelistToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "whitelistedTokens",
    data: BytesLike
  ): Result;

  events: {
    "MaxFeePctChanged(uint128)": EventFragment;
    "OwnerUpdated(address,address)": EventFragment;
    "SafeBlockThresholdChanged(uint256)": EventFragment;
    "TokenWhitelisted(address,bool)": EventFragment;
    "TradeDisputed(address,bytes32,bytes32,uint256,uint256)": EventFragment;
    "TradeFilled(address,bytes32,uint256,uint256,uint256)": EventFragment;
    "TradeRequested(address,address,uint256,uint256,address,uint256)": EventFragment;
    "TradeSettled(address,bytes32,uint256,uint256)": EventFragment;
    "UpdatedFeeForTrade(address,bytes32,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "MaxFeePctChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnerUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SafeBlockThresholdChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokenWhitelisted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TradeDisputed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TradeFilled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TradeRequested"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TradeSettled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UpdatedFeeForTrade"): EventFragment;
}

export interface MaxFeePctChangedEventObject {
  newMaxFeePct: BigNumber;
}
export type MaxFeePctChangedEvent = TypedEvent<
  [BigNumber],
  MaxFeePctChangedEventObject
>;

export type MaxFeePctChangedEventFilter =
  TypedEventFilter<MaxFeePctChangedEvent>;

export interface OwnerUpdatedEventObject {
  user: string;
  newOwner: string;
}
export type OwnerUpdatedEvent = TypedEvent<
  [string, string],
  OwnerUpdatedEventObject
>;

export type OwnerUpdatedEventFilter = TypedEventFilter<OwnerUpdatedEvent>;

export interface SafeBlockThresholdChangedEventObject {
  newSafeBlockThreshold: BigNumber;
}
export type SafeBlockThresholdChangedEvent = TypedEvent<
  [BigNumber],
  SafeBlockThresholdChangedEventObject
>;

export type SafeBlockThresholdChangedEventFilter =
  TypedEventFilter<SafeBlockThresholdChangedEvent>;

export interface TokenWhitelistedEventObject {
  token: string;
  whitelisted: boolean;
}
export type TokenWhitelistedEvent = TypedEvent<
  [string, boolean],
  TokenWhitelistedEventObject
>;

export type TokenWhitelistedEventFilter =
  TypedEventFilter<TokenWhitelistedEvent>;

export interface TradeDisputedEventObject {
  relayer: string;
  tradeId: string;
  disputeId: string;
  filledAmount: BigNumber;
  feePct: BigNumber;
}
export type TradeDisputedEvent = TypedEvent<
  [string, string, string, BigNumber, BigNumber],
  TradeDisputedEventObject
>;

export type TradeDisputedEventFilter = TypedEventFilter<TradeDisputedEvent>;

export interface TradeFilledEventObject {
  relayer: string;
  tradeId: string;
  filledAtBlock: BigNumber;
  feePct: BigNumber;
  amountOut: BigNumber;
}
export type TradeFilledEvent = TypedEvent<
  [string, string, BigNumber, BigNumber, BigNumber],
  TradeFilledEventObject
>;

export type TradeFilledEventFilter = TypedEventFilter<TradeFilledEvent>;

export interface TradeRequestedEventObject {
  tokenIn: string;
  tokenOut: string;
  amountIn: BigNumber;
  feePct: BigNumber;
  to: string;
  tradeIndex: BigNumber;
}
export type TradeRequestedEvent = TypedEvent<
  [string, string, BigNumber, BigNumber, string, BigNumber],
  TradeRequestedEventObject
>;

export type TradeRequestedEventFilter = TypedEventFilter<TradeRequestedEvent>;

export interface TradeSettledEventObject {
  relayer: string;
  tradeId: string;
  filledAmount: BigNumber;
  feePct: BigNumber;
}
export type TradeSettledEvent = TypedEvent<
  [string, string, BigNumber, BigNumber],
  TradeSettledEventObject
>;

export type TradeSettledEventFilter = TypedEventFilter<TradeSettledEvent>;

export interface UpdatedFeeForTradeEventObject {
  trader: string;
  tradeId: string;
  newFeePct: BigNumber;
}
export type UpdatedFeeForTradeEvent = TypedEvent<
  [string, string, BigNumber],
  UpdatedFeeForTradeEventObject
>;

export type UpdatedFeeForTradeEventFilter =
  TypedEventFilter<UpdatedFeeForTradeEvent>;

export interface BookSingleChain extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: BookSingleChainInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    disputeTrade(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      feePct: PromiseOrValue<BigNumberish>,
      to: PromiseOrValue<string>,
      tradeIndex: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    fillTrade(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      feePct: PromiseOrValue<BigNumberish>,
      to: PromiseOrValue<string>,
      tradeIndex: PromiseOrValue<BigNumberish>,
      amountToSend: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    fillTradeWithUpdatedFee(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      feePct: PromiseOrValue<BigNumberish>,
      to: PromiseOrValue<string>,
      tradeIndex: PromiseOrValue<BigNumberish>,
      amountToSend: PromiseOrValue<BigNumberish>,
      trader: PromiseOrValue<string>,
      newFeePct: PromiseOrValue<BigNumberish>,
      traderSignature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    filledAmount(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    filledAtBlock(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    filledBy(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    maxFeePct(overrides?: CallOverrides): Promise<[BigNumber]>;

    numberOfTrades(overrides?: CallOverrides): Promise<[BigNumber]>;

    oracle(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    requestTrade(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      feePct: PromiseOrValue<BigNumberish>,
      to: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    safeBlockThreshold(overrides?: CallOverrides): Promise<[BigNumber]>;

    setMaxFeePct(
      newMaxFeePct: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setOwner(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setSafeBlockThreshold(
      newSafeBlockThreshold: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    settleTrade(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      feePct: PromiseOrValue<BigNumberish>,
      to: PromiseOrValue<string>,
      tradeIndex: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateFeeForTrade(
      trader: PromiseOrValue<string>,
      tradeId: PromiseOrValue<BytesLike>,
      newFeePct: PromiseOrValue<BigNumberish>,
      traderSignature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    whitelistToken(
      token: PromiseOrValue<string>,
      whitelisted: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    whitelistedTokens(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  disputeTrade(
    tokenIn: PromiseOrValue<string>,
    tokenOut: PromiseOrValue<string>,
    amountIn: PromiseOrValue<BigNumberish>,
    feePct: PromiseOrValue<BigNumberish>,
    to: PromiseOrValue<string>,
    tradeIndex: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  fillTrade(
    tokenIn: PromiseOrValue<string>,
    tokenOut: PromiseOrValue<string>,
    amountIn: PromiseOrValue<BigNumberish>,
    feePct: PromiseOrValue<BigNumberish>,
    to: PromiseOrValue<string>,
    tradeIndex: PromiseOrValue<BigNumberish>,
    amountToSend: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  fillTradeWithUpdatedFee(
    tokenIn: PromiseOrValue<string>,
    tokenOut: PromiseOrValue<string>,
    amountIn: PromiseOrValue<BigNumberish>,
    feePct: PromiseOrValue<BigNumberish>,
    to: PromiseOrValue<string>,
    tradeIndex: PromiseOrValue<BigNumberish>,
    amountToSend: PromiseOrValue<BigNumberish>,
    trader: PromiseOrValue<string>,
    newFeePct: PromiseOrValue<BigNumberish>,
    traderSignature: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  filledAmount(
    arg0: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  filledAtBlock(
    arg0: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  filledBy(
    arg0: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  maxFeePct(overrides?: CallOverrides): Promise<BigNumber>;

  numberOfTrades(overrides?: CallOverrides): Promise<BigNumber>;

  oracle(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  requestTrade(
    tokenIn: PromiseOrValue<string>,
    tokenOut: PromiseOrValue<string>,
    amountIn: PromiseOrValue<BigNumberish>,
    feePct: PromiseOrValue<BigNumberish>,
    to: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  safeBlockThreshold(overrides?: CallOverrides): Promise<BigNumber>;

  setMaxFeePct(
    newMaxFeePct: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setOwner(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setSafeBlockThreshold(
    newSafeBlockThreshold: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  settleTrade(
    tokenIn: PromiseOrValue<string>,
    tokenOut: PromiseOrValue<string>,
    amountIn: PromiseOrValue<BigNumberish>,
    feePct: PromiseOrValue<BigNumberish>,
    to: PromiseOrValue<string>,
    tradeIndex: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateFeeForTrade(
    trader: PromiseOrValue<string>,
    tradeId: PromiseOrValue<BytesLike>,
    newFeePct: PromiseOrValue<BigNumberish>,
    traderSignature: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  whitelistToken(
    token: PromiseOrValue<string>,
    whitelisted: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  whitelistedTokens(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    disputeTrade(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      feePct: PromiseOrValue<BigNumberish>,
      to: PromiseOrValue<string>,
      tradeIndex: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    fillTrade(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      feePct: PromiseOrValue<BigNumberish>,
      to: PromiseOrValue<string>,
      tradeIndex: PromiseOrValue<BigNumberish>,
      amountToSend: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    fillTradeWithUpdatedFee(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      feePct: PromiseOrValue<BigNumberish>,
      to: PromiseOrValue<string>,
      tradeIndex: PromiseOrValue<BigNumberish>,
      amountToSend: PromiseOrValue<BigNumberish>,
      trader: PromiseOrValue<string>,
      newFeePct: PromiseOrValue<BigNumberish>,
      traderSignature: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    filledAmount(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    filledAtBlock(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    filledBy(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    maxFeePct(overrides?: CallOverrides): Promise<BigNumber>;

    numberOfTrades(overrides?: CallOverrides): Promise<BigNumber>;

    oracle(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    requestTrade(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      feePct: PromiseOrValue<BigNumberish>,
      to: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    safeBlockThreshold(overrides?: CallOverrides): Promise<BigNumber>;

    setMaxFeePct(
      newMaxFeePct: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setOwner(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setSafeBlockThreshold(
      newSafeBlockThreshold: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    settleTrade(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      feePct: PromiseOrValue<BigNumberish>,
      to: PromiseOrValue<string>,
      tradeIndex: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateFeeForTrade(
      trader: PromiseOrValue<string>,
      tradeId: PromiseOrValue<BytesLike>,
      newFeePct: PromiseOrValue<BigNumberish>,
      traderSignature: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    whitelistToken(
      token: PromiseOrValue<string>,
      whitelisted: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    whitelistedTokens(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {
    "MaxFeePctChanged(uint128)"(
      newMaxFeePct?: null
    ): MaxFeePctChangedEventFilter;
    MaxFeePctChanged(newMaxFeePct?: null): MaxFeePctChangedEventFilter;

    "OwnerUpdated(address,address)"(
      user?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnerUpdatedEventFilter;
    OwnerUpdated(
      user?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnerUpdatedEventFilter;

    "SafeBlockThresholdChanged(uint256)"(
      newSafeBlockThreshold?: null
    ): SafeBlockThresholdChangedEventFilter;
    SafeBlockThresholdChanged(
      newSafeBlockThreshold?: null
    ): SafeBlockThresholdChangedEventFilter;

    "TokenWhitelisted(address,bool)"(
      token?: PromiseOrValue<string> | null,
      whitelisted?: null
    ): TokenWhitelistedEventFilter;
    TokenWhitelisted(
      token?: PromiseOrValue<string> | null,
      whitelisted?: null
    ): TokenWhitelistedEventFilter;

    "TradeDisputed(address,bytes32,bytes32,uint256,uint256)"(
      relayer?: PromiseOrValue<string> | null,
      tradeId?: PromiseOrValue<BytesLike> | null,
      disputeId?: PromiseOrValue<BytesLike> | null,
      filledAmount?: null,
      feePct?: null
    ): TradeDisputedEventFilter;
    TradeDisputed(
      relayer?: PromiseOrValue<string> | null,
      tradeId?: PromiseOrValue<BytesLike> | null,
      disputeId?: PromiseOrValue<BytesLike> | null,
      filledAmount?: null,
      feePct?: null
    ): TradeDisputedEventFilter;

    "TradeFilled(address,bytes32,uint256,uint256,uint256)"(
      relayer?: PromiseOrValue<string> | null,
      tradeId?: PromiseOrValue<BytesLike> | null,
      filledAtBlock?: PromiseOrValue<BigNumberish> | null,
      feePct?: null,
      amountOut?: null
    ): TradeFilledEventFilter;
    TradeFilled(
      relayer?: PromiseOrValue<string> | null,
      tradeId?: PromiseOrValue<BytesLike> | null,
      filledAtBlock?: PromiseOrValue<BigNumberish> | null,
      feePct?: null,
      amountOut?: null
    ): TradeFilledEventFilter;

    "TradeRequested(address,address,uint256,uint256,address,uint256)"(
      tokenIn?: PromiseOrValue<string> | null,
      tokenOut?: PromiseOrValue<string> | null,
      amountIn?: null,
      feePct?: null,
      to?: null,
      tradeIndex?: PromiseOrValue<BigNumberish> | null
    ): TradeRequestedEventFilter;
    TradeRequested(
      tokenIn?: PromiseOrValue<string> | null,
      tokenOut?: PromiseOrValue<string> | null,
      amountIn?: null,
      feePct?: null,
      to?: null,
      tradeIndex?: PromiseOrValue<BigNumberish> | null
    ): TradeRequestedEventFilter;

    "TradeSettled(address,bytes32,uint256,uint256)"(
      relayer?: PromiseOrValue<string> | null,
      tradeId?: PromiseOrValue<BytesLike> | null,
      filledAmount?: PromiseOrValue<BigNumberish> | null,
      feePct?: null
    ): TradeSettledEventFilter;
    TradeSettled(
      relayer?: PromiseOrValue<string> | null,
      tradeId?: PromiseOrValue<BytesLike> | null,
      filledAmount?: PromiseOrValue<BigNumberish> | null,
      feePct?: null
    ): TradeSettledEventFilter;

    "UpdatedFeeForTrade(address,bytes32,uint256)"(
      trader?: PromiseOrValue<string> | null,
      tradeId?: PromiseOrValue<BytesLike> | null,
      newFeePct?: null
    ): UpdatedFeeForTradeEventFilter;
    UpdatedFeeForTrade(
      trader?: PromiseOrValue<string> | null,
      tradeId?: PromiseOrValue<BytesLike> | null,
      newFeePct?: null
    ): UpdatedFeeForTradeEventFilter;
  };

  estimateGas: {
    disputeTrade(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      feePct: PromiseOrValue<BigNumberish>,
      to: PromiseOrValue<string>,
      tradeIndex: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    fillTrade(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      feePct: PromiseOrValue<BigNumberish>,
      to: PromiseOrValue<string>,
      tradeIndex: PromiseOrValue<BigNumberish>,
      amountToSend: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    fillTradeWithUpdatedFee(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      feePct: PromiseOrValue<BigNumberish>,
      to: PromiseOrValue<string>,
      tradeIndex: PromiseOrValue<BigNumberish>,
      amountToSend: PromiseOrValue<BigNumberish>,
      trader: PromiseOrValue<string>,
      newFeePct: PromiseOrValue<BigNumberish>,
      traderSignature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    filledAmount(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    filledAtBlock(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    filledBy(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    maxFeePct(overrides?: CallOverrides): Promise<BigNumber>;

    numberOfTrades(overrides?: CallOverrides): Promise<BigNumber>;

    oracle(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    requestTrade(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      feePct: PromiseOrValue<BigNumberish>,
      to: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    safeBlockThreshold(overrides?: CallOverrides): Promise<BigNumber>;

    setMaxFeePct(
      newMaxFeePct: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setOwner(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setSafeBlockThreshold(
      newSafeBlockThreshold: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    settleTrade(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      feePct: PromiseOrValue<BigNumberish>,
      to: PromiseOrValue<string>,
      tradeIndex: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateFeeForTrade(
      trader: PromiseOrValue<string>,
      tradeId: PromiseOrValue<BytesLike>,
      newFeePct: PromiseOrValue<BigNumberish>,
      traderSignature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    whitelistToken(
      token: PromiseOrValue<string>,
      whitelisted: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    whitelistedTokens(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    disputeTrade(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      feePct: PromiseOrValue<BigNumberish>,
      to: PromiseOrValue<string>,
      tradeIndex: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    fillTrade(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      feePct: PromiseOrValue<BigNumberish>,
      to: PromiseOrValue<string>,
      tradeIndex: PromiseOrValue<BigNumberish>,
      amountToSend: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    fillTradeWithUpdatedFee(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      feePct: PromiseOrValue<BigNumberish>,
      to: PromiseOrValue<string>,
      tradeIndex: PromiseOrValue<BigNumberish>,
      amountToSend: PromiseOrValue<BigNumberish>,
      trader: PromiseOrValue<string>,
      newFeePct: PromiseOrValue<BigNumberish>,
      traderSignature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    filledAmount(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    filledAtBlock(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    filledBy(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    maxFeePct(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    numberOfTrades(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    oracle(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    requestTrade(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      feePct: PromiseOrValue<BigNumberish>,
      to: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    safeBlockThreshold(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setMaxFeePct(
      newMaxFeePct: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setOwner(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setSafeBlockThreshold(
      newSafeBlockThreshold: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    settleTrade(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      feePct: PromiseOrValue<BigNumberish>,
      to: PromiseOrValue<string>,
      tradeIndex: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateFeeForTrade(
      trader: PromiseOrValue<string>,
      tradeId: PromiseOrValue<BytesLike>,
      newFeePct: PromiseOrValue<BigNumberish>,
      traderSignature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    whitelistToken(
      token: PromiseOrValue<string>,
      whitelisted: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    whitelistedTokens(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
