/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as allKnowingOracleSol from "./AllKnowingOracle.sol";
export type { allKnowingOracleSol };
import type * as bookSingleChainSol from "./BookSingleChain.sol";
export type { bookSingleChainSol };
export type { ERC20 } from "./ERC20";
export type { Owned } from "./Owned";
export * as factories from "./factories";
export type { AllKnowingOracle } from "./AllKnowingOracle.sol/AllKnowingOracle";
export { AllKnowingOracle__factory } from "./factories/AllKnowingOracle.sol/AllKnowingOracle__factory";
export type { IAllKnowingOracleEvents } from "./AllKnowingOracle.sol/IAllKnowingOracleEvents";
export { IAllKnowingOracleEvents__factory } from "./factories/AllKnowingOracle.sol/IAllKnowingOracleEvents__factory";
export type { IOptimisticRequester } from "./AllKnowingOracle.sol/IOptimisticRequester";
export { IOptimisticRequester__factory } from "./factories/AllKnowingOracle.sol/IOptimisticRequester__factory";
export type { IOracle } from "./AllKnowingOracle.sol/IOracle";
export { IOracle__factory } from "./factories/AllKnowingOracle.sol/IOracle__factory";
export type { BookSingleChain } from "./BookSingleChain.sol/BookSingleChain";
export { BookSingleChain__factory } from "./factories/BookSingleChain.sol/BookSingleChain__factory";
export type { IBookSingleChainEvents } from "./BookSingleChain.sol/IBookSingleChainEvents";
export { IBookSingleChainEvents__factory } from "./factories/BookSingleChain.sol/IBookSingleChainEvents__factory";
export { ERC20__factory } from "./factories/ERC20__factory";
export { Owned__factory } from "./factories/Owned__factory";
