/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as allKnowingOracleSol from "./AllKnowingOracle.sol";
export type { allKnowingOracleSol };
import type * as bookSol from "./Book.sol";
export type { bookSol };
export type { ERC20 } from "./ERC20";
export type { Owned } from "./Owned";
export * as factories from "./factories";
export type { AllKnowingOracle } from "./AllKnowingOracle.sol/AllKnowingOracle";
export { AllKnowingOracle__factory } from "./factories/AllKnowingOracle.sol/AllKnowingOracle__factory";
export type { IAllKnowingOracleEvents } from "./AllKnowingOracle.sol/IAllKnowingOracleEvents";
export { IAllKnowingOracleEvents__factory } from "./factories/AllKnowingOracle.sol/IAllKnowingOracleEvents__factory";
export type { IOptimisticRequester } from "./AllKnowingOracle.sol/IOptimisticRequester";
export { IOptimisticRequester__factory } from "./factories/AllKnowingOracle.sol/IOptimisticRequester__factory";
export type { Book } from "./Book.sol/Book";
export { Book__factory } from "./factories/Book.sol/Book__factory";
export type { IBookEvents } from "./Book.sol/IBookEvents";
export { IBookEvents__factory } from "./factories/Book.sol/IBookEvents__factory";
export { ERC20__factory } from "./factories/ERC20__factory";
export { Owned__factory } from "./factories/Owned__factory";
