#![allow(clippy::all)]
//! This lib contains abigen! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub mod erc20;
pub mod flood_plain;
pub mod i_auth_zone;
pub mod i_signature_transfer;
pub mod ieip712;
pub mod shared_types;
pub mod zone;
