/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export type RequestStruct = {
  requester: PromiseOrValue<string>;
  proposer: PromiseOrValue<string>;
  disputer: PromiseOrValue<string>;
  currency: PromiseOrValue<string>;
  bond: PromiseOrValue<BigNumberish>;
  state: PromiseOrValue<BigNumberish>;
  answer: PromiseOrValue<boolean>;
  data: PromiseOrValue<BytesLike>;
};

export type RequestStructOutput = [
  string,
  string,
  string,
  string,
  BigNumber,
  number,
  boolean,
  string
] & {
  requester: string;
  proposer: string;
  disputer: string;
  currency: string;
  bond: BigNumber;
  state: number;
  answer: boolean;
  data: string;
};

export interface BookSingleChainInterface extends utils.Interface {
  functions: {
    "disputeBondPct()": FunctionFragment;
    "disputeTrade(address,address,uint256,uint256,uint256,address,uint256)": FunctionFragment;
    "fillTrade(address,address,uint256,uint256,uint256,address,uint256,uint256)": FunctionFragment;
    "fillTradeWithUpdatedFee(address,address,uint256,uint256,uint256,address,uint256,uint256,address,uint256,bytes)": FunctionFragment;
    "filledAtBlock(bytes32)": FunctionFragment;
    "filledBy(bytes32)": FunctionFragment;
    "numberOfTrades()": FunctionFragment;
    "onPriceSettled(bytes32,(address,address,address,address,uint256,uint8,bool,bytes))": FunctionFragment;
    "oracle()": FunctionFragment;
    "owner()": FunctionFragment;
    "relayerRefundPct()": FunctionFragment;
    "requestTrade(address,address,uint256,uint256,uint256,address)": FunctionFragment;
    "safeBlockThreshold()": FunctionFragment;
    "setOwner(address)": FunctionFragment;
    "settleTrade(address,address,uint256,uint256,uint256,address,uint256)": FunctionFragment;
    "tradeRebatePct()": FunctionFragment;
    "updateFeeForTrade(address,address,uint256,uint256,uint256,address,uint256,address,uint256,bytes)": FunctionFragment;
    "whitelistToken(address,bool)": FunctionFragment;
    "whitelistedTokens(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "disputeBondPct"
      | "disputeTrade"
      | "fillTrade"
      | "fillTradeWithUpdatedFee"
      | "filledAtBlock"
      | "filledBy"
      | "numberOfTrades"
      | "onPriceSettled"
      | "oracle"
      | "owner"
      | "relayerRefundPct"
      | "requestTrade"
      | "safeBlockThreshold"
      | "setOwner"
      | "settleTrade"
      | "tradeRebatePct"
      | "updateFeeForTrade"
      | "whitelistToken"
      | "whitelistedTokens"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "disputeBondPct",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "disputeTrade",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "fillTrade",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "fillTradeWithUpdatedFee",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "filledAtBlock",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "filledBy",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "numberOfTrades",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "onPriceSettled",
    values: [PromiseOrValue<BytesLike>, RequestStruct]
  ): string;
  encodeFunctionData(functionFragment: "oracle", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "relayerRefundPct",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestTrade",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "safeBlockThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setOwner",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "settleTrade",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "tradeRebatePct",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateFeeForTrade",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistToken",
    values: [PromiseOrValue<string>, PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistedTokens",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "disputeBondPct",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disputeTrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fillTrade", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fillTradeWithUpdatedFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "filledAtBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "filledBy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "numberOfTrades",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onPriceSettled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "oracle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "relayerRefundPct",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestTrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeBlockThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setOwner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "settleTrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tradeRebatePct",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateFeeForTrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "whitelistToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "whitelistedTokens",
    data: BytesLike
  ): Result;

  events: {
    "FeeCombinationSet(uint256,uint256,uint256)": EventFragment;
    "OwnerUpdated(address,address)": EventFragment;
    "SafeBlockThresholdSet(uint256)": EventFragment;
    "TokenWhitelisted(address,bool)": EventFragment;
    "TradeDisputeSettled(address,uint256,bytes32,bool)": EventFragment;
    "TradeDisputed(address,uint256,bytes32,uint256)": EventFragment;
    "TradeFilled(address,uint256,uint256,uint256)": EventFragment;
    "TradeRequested(address,address,uint256,uint256,uint256,address,uint256)": EventFragment;
    "TradeSettled(address,uint256,uint256)": EventFragment;
    "UpdatedFeeForTrade(address,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "FeeCombinationSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnerUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SafeBlockThresholdSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokenWhitelisted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TradeDisputeSettled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TradeDisputed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TradeFilled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TradeRequested"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TradeSettled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UpdatedFeeForTrade"): EventFragment;
}

export interface FeeCombinationSetEventObject {
  disputeBondPct: BigNumber;
  tradeRebatePct: BigNumber;
  relayerRefundPct: BigNumber;
}
export type FeeCombinationSetEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber],
  FeeCombinationSetEventObject
>;

export type FeeCombinationSetEventFilter =
  TypedEventFilter<FeeCombinationSetEvent>;

export interface OwnerUpdatedEventObject {
  user: string;
  newOwner: string;
}
export type OwnerUpdatedEvent = TypedEvent<
  [string, string],
  OwnerUpdatedEventObject
>;

export type OwnerUpdatedEventFilter = TypedEventFilter<OwnerUpdatedEvent>;

export interface SafeBlockThresholdSetEventObject {
  newSafeBlockThreshold: BigNumber;
}
export type SafeBlockThresholdSetEvent = TypedEvent<
  [BigNumber],
  SafeBlockThresholdSetEventObject
>;

export type SafeBlockThresholdSetEventFilter =
  TypedEventFilter<SafeBlockThresholdSetEvent>;

export interface TokenWhitelistedEventObject {
  token: string;
  whitelisted: boolean;
}
export type TokenWhitelistedEvent = TypedEvent<
  [string, boolean],
  TokenWhitelistedEventObject
>;

export type TokenWhitelistedEventFilter =
  TypedEventFilter<TokenWhitelistedEvent>;

export interface TradeDisputeSettledEventObject {
  relayer: string;
  tradeIndex: BigNumber;
  disputeId: string;
  answer: boolean;
}
export type TradeDisputeSettledEvent = TypedEvent<
  [string, BigNumber, string, boolean],
  TradeDisputeSettledEventObject
>;

export type TradeDisputeSettledEventFilter =
  TypedEventFilter<TradeDisputeSettledEvent>;

export interface TradeDisputedEventObject {
  relayer: string;
  tradeIndex: BigNumber;
  disputeId: string;
  filledAtBlock: BigNumber;
}
export type TradeDisputedEvent = TypedEvent<
  [string, BigNumber, string, BigNumber],
  TradeDisputedEventObject
>;

export type TradeDisputedEventFilter = TypedEventFilter<TradeDisputedEvent>;

export interface TradeFilledEventObject {
  relayer: string;
  tradeIndex: BigNumber;
  feePct: BigNumber;
  amountOut: BigNumber;
}
export type TradeFilledEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber],
  TradeFilledEventObject
>;

export type TradeFilledEventFilter = TypedEventFilter<TradeFilledEvent>;

export interface TradeRequestedEventObject {
  tokenIn: string;
  tokenOut: string;
  amountIn: BigNumber;
  minAmountOut: BigNumber;
  feePct: BigNumber;
  to: string;
  tradeIndex: BigNumber;
}
export type TradeRequestedEvent = TypedEvent<
  [string, string, BigNumber, BigNumber, BigNumber, string, BigNumber],
  TradeRequestedEventObject
>;

export type TradeRequestedEventFilter = TypedEventFilter<TradeRequestedEvent>;

export interface TradeSettledEventObject {
  relayer: string;
  tradeIndex: BigNumber;
  filledAtBlock: BigNumber;
}
export type TradeSettledEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  TradeSettledEventObject
>;

export type TradeSettledEventFilter = TypedEventFilter<TradeSettledEvent>;

export interface UpdatedFeeForTradeEventObject {
  trader: string;
  tradeIndex: BigNumber;
  newFeePct: BigNumber;
}
export type UpdatedFeeForTradeEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  UpdatedFeeForTradeEventObject
>;

export type UpdatedFeeForTradeEventFilter =
  TypedEventFilter<UpdatedFeeForTradeEvent>;

export interface BookSingleChain extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: BookSingleChainInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    disputeBondPct(overrides?: CallOverrides): Promise<[BigNumber]>;

    disputeTrade(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      minAmountOut: PromiseOrValue<BigNumberish>,
      feePct: PromiseOrValue<BigNumberish>,
      recipient: PromiseOrValue<string>,
      tradeIndex: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    fillTrade(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      minAmountOut: PromiseOrValue<BigNumberish>,
      feePct: PromiseOrValue<BigNumberish>,
      recipient: PromiseOrValue<string>,
      tradeIndex: PromiseOrValue<BigNumberish>,
      amountToSend: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    fillTradeWithUpdatedFee(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      minAmountOut: PromiseOrValue<BigNumberish>,
      feePct: PromiseOrValue<BigNumberish>,
      recipient: PromiseOrValue<string>,
      tradeIndex: PromiseOrValue<BigNumberish>,
      amountToSend: PromiseOrValue<BigNumberish>,
      trader: PromiseOrValue<string>,
      newFeePct: PromiseOrValue<BigNumberish>,
      traderSignature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    filledAtBlock(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    filledBy(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    numberOfTrades(overrides?: CallOverrides): Promise<[BigNumber]>;

    onPriceSettled(
      id: PromiseOrValue<BytesLike>,
      request: RequestStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    oracle(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    relayerRefundPct(overrides?: CallOverrides): Promise<[BigNumber]>;

    requestTrade(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      minAmountOut: PromiseOrValue<BigNumberish>,
      feePct: PromiseOrValue<BigNumberish>,
      recipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    safeBlockThreshold(overrides?: CallOverrides): Promise<[BigNumber]>;

    setOwner(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    settleTrade(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      minAmountOut: PromiseOrValue<BigNumberish>,
      feePct: PromiseOrValue<BigNumberish>,
      recipient: PromiseOrValue<string>,
      tradeIndex: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    tradeRebatePct(overrides?: CallOverrides): Promise<[BigNumber]>;

    updateFeeForTrade(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      minAmountOut: PromiseOrValue<BigNumberish>,
      feePct: PromiseOrValue<BigNumberish>,
      recipient: PromiseOrValue<string>,
      tradeIndex: PromiseOrValue<BigNumberish>,
      trader: PromiseOrValue<string>,
      newFeePct: PromiseOrValue<BigNumberish>,
      traderSignature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    whitelistToken(
      token: PromiseOrValue<string>,
      whitelisted: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    whitelistedTokens(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  disputeBondPct(overrides?: CallOverrides): Promise<BigNumber>;

  disputeTrade(
    tokenIn: PromiseOrValue<string>,
    tokenOut: PromiseOrValue<string>,
    amountIn: PromiseOrValue<BigNumberish>,
    minAmountOut: PromiseOrValue<BigNumberish>,
    feePct: PromiseOrValue<BigNumberish>,
    recipient: PromiseOrValue<string>,
    tradeIndex: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  fillTrade(
    tokenIn: PromiseOrValue<string>,
    tokenOut: PromiseOrValue<string>,
    amountIn: PromiseOrValue<BigNumberish>,
    minAmountOut: PromiseOrValue<BigNumberish>,
    feePct: PromiseOrValue<BigNumberish>,
    recipient: PromiseOrValue<string>,
    tradeIndex: PromiseOrValue<BigNumberish>,
    amountToSend: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  fillTradeWithUpdatedFee(
    tokenIn: PromiseOrValue<string>,
    tokenOut: PromiseOrValue<string>,
    amountIn: PromiseOrValue<BigNumberish>,
    minAmountOut: PromiseOrValue<BigNumberish>,
    feePct: PromiseOrValue<BigNumberish>,
    recipient: PromiseOrValue<string>,
    tradeIndex: PromiseOrValue<BigNumberish>,
    amountToSend: PromiseOrValue<BigNumberish>,
    trader: PromiseOrValue<string>,
    newFeePct: PromiseOrValue<BigNumberish>,
    traderSignature: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  filledAtBlock(
    arg0: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  filledBy(
    arg0: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  numberOfTrades(overrides?: CallOverrides): Promise<BigNumber>;

  onPriceSettled(
    id: PromiseOrValue<BytesLike>,
    request: RequestStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  oracle(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  relayerRefundPct(overrides?: CallOverrides): Promise<BigNumber>;

  requestTrade(
    tokenIn: PromiseOrValue<string>,
    tokenOut: PromiseOrValue<string>,
    amountIn: PromiseOrValue<BigNumberish>,
    minAmountOut: PromiseOrValue<BigNumberish>,
    feePct: PromiseOrValue<BigNumberish>,
    recipient: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  safeBlockThreshold(overrides?: CallOverrides): Promise<BigNumber>;

  setOwner(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  settleTrade(
    tokenIn: PromiseOrValue<string>,
    tokenOut: PromiseOrValue<string>,
    amountIn: PromiseOrValue<BigNumberish>,
    minAmountOut: PromiseOrValue<BigNumberish>,
    feePct: PromiseOrValue<BigNumberish>,
    recipient: PromiseOrValue<string>,
    tradeIndex: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  tradeRebatePct(overrides?: CallOverrides): Promise<BigNumber>;

  updateFeeForTrade(
    tokenIn: PromiseOrValue<string>,
    tokenOut: PromiseOrValue<string>,
    amountIn: PromiseOrValue<BigNumberish>,
    minAmountOut: PromiseOrValue<BigNumberish>,
    feePct: PromiseOrValue<BigNumberish>,
    recipient: PromiseOrValue<string>,
    tradeIndex: PromiseOrValue<BigNumberish>,
    trader: PromiseOrValue<string>,
    newFeePct: PromiseOrValue<BigNumberish>,
    traderSignature: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  whitelistToken(
    token: PromiseOrValue<string>,
    whitelisted: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  whitelistedTokens(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    disputeBondPct(overrides?: CallOverrides): Promise<BigNumber>;

    disputeTrade(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      minAmountOut: PromiseOrValue<BigNumberish>,
      feePct: PromiseOrValue<BigNumberish>,
      recipient: PromiseOrValue<string>,
      tradeIndex: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    fillTrade(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      minAmountOut: PromiseOrValue<BigNumberish>,
      feePct: PromiseOrValue<BigNumberish>,
      recipient: PromiseOrValue<string>,
      tradeIndex: PromiseOrValue<BigNumberish>,
      amountToSend: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    fillTradeWithUpdatedFee(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      minAmountOut: PromiseOrValue<BigNumberish>,
      feePct: PromiseOrValue<BigNumberish>,
      recipient: PromiseOrValue<string>,
      tradeIndex: PromiseOrValue<BigNumberish>,
      amountToSend: PromiseOrValue<BigNumberish>,
      trader: PromiseOrValue<string>,
      newFeePct: PromiseOrValue<BigNumberish>,
      traderSignature: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    filledAtBlock(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    filledBy(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    numberOfTrades(overrides?: CallOverrides): Promise<BigNumber>;

    onPriceSettled(
      id: PromiseOrValue<BytesLike>,
      request: RequestStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    oracle(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    relayerRefundPct(overrides?: CallOverrides): Promise<BigNumber>;

    requestTrade(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      minAmountOut: PromiseOrValue<BigNumberish>,
      feePct: PromiseOrValue<BigNumberish>,
      recipient: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    safeBlockThreshold(overrides?: CallOverrides): Promise<BigNumber>;

    setOwner(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    settleTrade(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      minAmountOut: PromiseOrValue<BigNumberish>,
      feePct: PromiseOrValue<BigNumberish>,
      recipient: PromiseOrValue<string>,
      tradeIndex: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    tradeRebatePct(overrides?: CallOverrides): Promise<BigNumber>;

    updateFeeForTrade(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      minAmountOut: PromiseOrValue<BigNumberish>,
      feePct: PromiseOrValue<BigNumberish>,
      recipient: PromiseOrValue<string>,
      tradeIndex: PromiseOrValue<BigNumberish>,
      trader: PromiseOrValue<string>,
      newFeePct: PromiseOrValue<BigNumberish>,
      traderSignature: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    whitelistToken(
      token: PromiseOrValue<string>,
      whitelisted: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    whitelistedTokens(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {
    "FeeCombinationSet(uint256,uint256,uint256)"(
      disputeBondPct?: null,
      tradeRebatePct?: null,
      relayerRefundPct?: null
    ): FeeCombinationSetEventFilter;
    FeeCombinationSet(
      disputeBondPct?: null,
      tradeRebatePct?: null,
      relayerRefundPct?: null
    ): FeeCombinationSetEventFilter;

    "OwnerUpdated(address,address)"(
      user?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnerUpdatedEventFilter;
    OwnerUpdated(
      user?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnerUpdatedEventFilter;

    "SafeBlockThresholdSet(uint256)"(
      newSafeBlockThreshold?: null
    ): SafeBlockThresholdSetEventFilter;
    SafeBlockThresholdSet(
      newSafeBlockThreshold?: null
    ): SafeBlockThresholdSetEventFilter;

    "TokenWhitelisted(address,bool)"(
      token?: PromiseOrValue<string> | null,
      whitelisted?: null
    ): TokenWhitelistedEventFilter;
    TokenWhitelisted(
      token?: PromiseOrValue<string> | null,
      whitelisted?: null
    ): TokenWhitelistedEventFilter;

    "TradeDisputeSettled(address,uint256,bytes32,bool)"(
      relayer?: PromiseOrValue<string> | null,
      tradeIndex?: PromiseOrValue<BigNumberish> | null,
      disputeId?: PromiseOrValue<BytesLike> | null,
      answer?: null
    ): TradeDisputeSettledEventFilter;
    TradeDisputeSettled(
      relayer?: PromiseOrValue<string> | null,
      tradeIndex?: PromiseOrValue<BigNumberish> | null,
      disputeId?: PromiseOrValue<BytesLike> | null,
      answer?: null
    ): TradeDisputeSettledEventFilter;

    "TradeDisputed(address,uint256,bytes32,uint256)"(
      relayer?: PromiseOrValue<string> | null,
      tradeIndex?: PromiseOrValue<BigNumberish> | null,
      disputeId?: PromiseOrValue<BytesLike> | null,
      filledAtBlock?: null
    ): TradeDisputedEventFilter;
    TradeDisputed(
      relayer?: PromiseOrValue<string> | null,
      tradeIndex?: PromiseOrValue<BigNumberish> | null,
      disputeId?: PromiseOrValue<BytesLike> | null,
      filledAtBlock?: null
    ): TradeDisputedEventFilter;

    "TradeFilled(address,uint256,uint256,uint256)"(
      relayer?: PromiseOrValue<string> | null,
      tradeIndex?: PromiseOrValue<BigNumberish> | null,
      feePct?: null,
      amountOut?: null
    ): TradeFilledEventFilter;
    TradeFilled(
      relayer?: PromiseOrValue<string> | null,
      tradeIndex?: PromiseOrValue<BigNumberish> | null,
      feePct?: null,
      amountOut?: null
    ): TradeFilledEventFilter;

    "TradeRequested(address,address,uint256,uint256,uint256,address,uint256)"(
      tokenIn?: PromiseOrValue<string> | null,
      tokenOut?: PromiseOrValue<string> | null,
      amountIn?: null,
      minAmountOut?: null,
      feePct?: null,
      to?: null,
      tradeIndex?: PromiseOrValue<BigNumberish> | null
    ): TradeRequestedEventFilter;
    TradeRequested(
      tokenIn?: PromiseOrValue<string> | null,
      tokenOut?: PromiseOrValue<string> | null,
      amountIn?: null,
      minAmountOut?: null,
      feePct?: null,
      to?: null,
      tradeIndex?: PromiseOrValue<BigNumberish> | null
    ): TradeRequestedEventFilter;

    "TradeSettled(address,uint256,uint256)"(
      relayer?: PromiseOrValue<string> | null,
      tradeIndex?: PromiseOrValue<BigNumberish> | null,
      filledAtBlock?: null
    ): TradeSettledEventFilter;
    TradeSettled(
      relayer?: PromiseOrValue<string> | null,
      tradeIndex?: PromiseOrValue<BigNumberish> | null,
      filledAtBlock?: null
    ): TradeSettledEventFilter;

    "UpdatedFeeForTrade(address,uint256,uint256)"(
      trader?: PromiseOrValue<string> | null,
      tradeIndex?: PromiseOrValue<BigNumberish> | null,
      newFeePct?: null
    ): UpdatedFeeForTradeEventFilter;
    UpdatedFeeForTrade(
      trader?: PromiseOrValue<string> | null,
      tradeIndex?: PromiseOrValue<BigNumberish> | null,
      newFeePct?: null
    ): UpdatedFeeForTradeEventFilter;
  };

  estimateGas: {
    disputeBondPct(overrides?: CallOverrides): Promise<BigNumber>;

    disputeTrade(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      minAmountOut: PromiseOrValue<BigNumberish>,
      feePct: PromiseOrValue<BigNumberish>,
      recipient: PromiseOrValue<string>,
      tradeIndex: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    fillTrade(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      minAmountOut: PromiseOrValue<BigNumberish>,
      feePct: PromiseOrValue<BigNumberish>,
      recipient: PromiseOrValue<string>,
      tradeIndex: PromiseOrValue<BigNumberish>,
      amountToSend: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    fillTradeWithUpdatedFee(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      minAmountOut: PromiseOrValue<BigNumberish>,
      feePct: PromiseOrValue<BigNumberish>,
      recipient: PromiseOrValue<string>,
      tradeIndex: PromiseOrValue<BigNumberish>,
      amountToSend: PromiseOrValue<BigNumberish>,
      trader: PromiseOrValue<string>,
      newFeePct: PromiseOrValue<BigNumberish>,
      traderSignature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    filledAtBlock(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    filledBy(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    numberOfTrades(overrides?: CallOverrides): Promise<BigNumber>;

    onPriceSettled(
      id: PromiseOrValue<BytesLike>,
      request: RequestStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    oracle(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    relayerRefundPct(overrides?: CallOverrides): Promise<BigNumber>;

    requestTrade(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      minAmountOut: PromiseOrValue<BigNumberish>,
      feePct: PromiseOrValue<BigNumberish>,
      recipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    safeBlockThreshold(overrides?: CallOverrides): Promise<BigNumber>;

    setOwner(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    settleTrade(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      minAmountOut: PromiseOrValue<BigNumberish>,
      feePct: PromiseOrValue<BigNumberish>,
      recipient: PromiseOrValue<string>,
      tradeIndex: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    tradeRebatePct(overrides?: CallOverrides): Promise<BigNumber>;

    updateFeeForTrade(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      minAmountOut: PromiseOrValue<BigNumberish>,
      feePct: PromiseOrValue<BigNumberish>,
      recipient: PromiseOrValue<string>,
      tradeIndex: PromiseOrValue<BigNumberish>,
      trader: PromiseOrValue<string>,
      newFeePct: PromiseOrValue<BigNumberish>,
      traderSignature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    whitelistToken(
      token: PromiseOrValue<string>,
      whitelisted: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    whitelistedTokens(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    disputeBondPct(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    disputeTrade(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      minAmountOut: PromiseOrValue<BigNumberish>,
      feePct: PromiseOrValue<BigNumberish>,
      recipient: PromiseOrValue<string>,
      tradeIndex: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    fillTrade(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      minAmountOut: PromiseOrValue<BigNumberish>,
      feePct: PromiseOrValue<BigNumberish>,
      recipient: PromiseOrValue<string>,
      tradeIndex: PromiseOrValue<BigNumberish>,
      amountToSend: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    fillTradeWithUpdatedFee(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      minAmountOut: PromiseOrValue<BigNumberish>,
      feePct: PromiseOrValue<BigNumberish>,
      recipient: PromiseOrValue<string>,
      tradeIndex: PromiseOrValue<BigNumberish>,
      amountToSend: PromiseOrValue<BigNumberish>,
      trader: PromiseOrValue<string>,
      newFeePct: PromiseOrValue<BigNumberish>,
      traderSignature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    filledAtBlock(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    filledBy(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    numberOfTrades(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    onPriceSettled(
      id: PromiseOrValue<BytesLike>,
      request: RequestStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    oracle(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    relayerRefundPct(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    requestTrade(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      minAmountOut: PromiseOrValue<BigNumberish>,
      feePct: PromiseOrValue<BigNumberish>,
      recipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    safeBlockThreshold(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setOwner(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    settleTrade(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      minAmountOut: PromiseOrValue<BigNumberish>,
      feePct: PromiseOrValue<BigNumberish>,
      recipient: PromiseOrValue<string>,
      tradeIndex: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    tradeRebatePct(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    updateFeeForTrade(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      minAmountOut: PromiseOrValue<BigNumberish>,
      feePct: PromiseOrValue<BigNumberish>,
      recipient: PromiseOrValue<string>,
      tradeIndex: PromiseOrValue<BigNumberish>,
      trader: PromiseOrValue<string>,
      newFeePct: PromiseOrValue<BigNumberish>,
      traderSignature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    whitelistToken(
      token: PromiseOrValue<string>,
      whitelisted: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    whitelistedTokens(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
