/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  Signer,
  utils,
} from "ethers";
import type { EventFragment } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface IBookSingleChainEventsInterface extends utils.Interface {
  functions: {};

  events: {
    "MaxFeePctChanged(uint256)": EventFragment;
    "SafeBlockThresholdChanged(uint256)": EventFragment;
    "TokenWhitelisted(address,bool)": EventFragment;
    "TradeDisputed(address,uint256,bytes32,uint256,uint256)": EventFragment;
    "TradeFilled(address,uint256,uint256,uint256)": EventFragment;
    "TradeRequested(address,address,uint256,uint256,address,uint256)": EventFragment;
    "TradeSettled(address,uint256,uint256,uint256)": EventFragment;
    "UpdatedFeeForTrade(address,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "MaxFeePctChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SafeBlockThresholdChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokenWhitelisted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TradeDisputed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TradeFilled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TradeRequested"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TradeSettled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UpdatedFeeForTrade"): EventFragment;
}

export interface MaxFeePctChangedEventObject {
  newMaxFeePct: BigNumber;
}
export type MaxFeePctChangedEvent = TypedEvent<
  [BigNumber],
  MaxFeePctChangedEventObject
>;

export type MaxFeePctChangedEventFilter =
  TypedEventFilter<MaxFeePctChangedEvent>;

export interface SafeBlockThresholdChangedEventObject {
  newSafeBlockThreshold: BigNumber;
}
export type SafeBlockThresholdChangedEvent = TypedEvent<
  [BigNumber],
  SafeBlockThresholdChangedEventObject
>;

export type SafeBlockThresholdChangedEventFilter =
  TypedEventFilter<SafeBlockThresholdChangedEvent>;

export interface TokenWhitelistedEventObject {
  token: string;
  whitelisted: boolean;
}
export type TokenWhitelistedEvent = TypedEvent<
  [string, boolean],
  TokenWhitelistedEventObject
>;

export type TokenWhitelistedEventFilter =
  TypedEventFilter<TokenWhitelistedEvent>;

export interface TradeDisputedEventObject {
  relayer: string;
  tradeIndex: BigNumber;
  disputeId: string;
  filledAmount: BigNumber;
  feePct: BigNumber;
}
export type TradeDisputedEvent = TypedEvent<
  [string, BigNumber, string, BigNumber, BigNumber],
  TradeDisputedEventObject
>;

export type TradeDisputedEventFilter = TypedEventFilter<TradeDisputedEvent>;

export interface TradeFilledEventObject {
  relayer: string;
  tradeIndex: BigNumber;
  feePct: BigNumber;
  amountOut: BigNumber;
}
export type TradeFilledEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber],
  TradeFilledEventObject
>;

export type TradeFilledEventFilter = TypedEventFilter<TradeFilledEvent>;

export interface TradeRequestedEventObject {
  tokenIn: string;
  tokenOut: string;
  amountIn: BigNumber;
  feePct: BigNumber;
  to: string;
  tradeIndex: BigNumber;
}
export type TradeRequestedEvent = TypedEvent<
  [string, string, BigNumber, BigNumber, string, BigNumber],
  TradeRequestedEventObject
>;

export type TradeRequestedEventFilter = TypedEventFilter<TradeRequestedEvent>;

export interface TradeSettledEventObject {
  relayer: string;
  tradeIndex: BigNumber;
  filledAmount: BigNumber;
  feePct: BigNumber;
}
export type TradeSettledEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber],
  TradeSettledEventObject
>;

export type TradeSettledEventFilter = TypedEventFilter<TradeSettledEvent>;

export interface UpdatedFeeForTradeEventObject {
  trader: string;
  tradeIndex: BigNumber;
  newFeePct: BigNumber;
}
export type UpdatedFeeForTradeEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  UpdatedFeeForTradeEventObject
>;

export type UpdatedFeeForTradeEventFilter =
  TypedEventFilter<UpdatedFeeForTradeEvent>;

export interface IBookSingleChainEvents extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IBookSingleChainEventsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {};

  callStatic: {};

  filters: {
    "MaxFeePctChanged(uint256)"(
      newMaxFeePct?: null
    ): MaxFeePctChangedEventFilter;
    MaxFeePctChanged(newMaxFeePct?: null): MaxFeePctChangedEventFilter;

    "SafeBlockThresholdChanged(uint256)"(
      newSafeBlockThreshold?: null
    ): SafeBlockThresholdChangedEventFilter;
    SafeBlockThresholdChanged(
      newSafeBlockThreshold?: null
    ): SafeBlockThresholdChangedEventFilter;

    "TokenWhitelisted(address,bool)"(
      token?: PromiseOrValue<string> | null,
      whitelisted?: null
    ): TokenWhitelistedEventFilter;
    TokenWhitelisted(
      token?: PromiseOrValue<string> | null,
      whitelisted?: null
    ): TokenWhitelistedEventFilter;

    "TradeDisputed(address,uint256,bytes32,uint256,uint256)"(
      relayer?: PromiseOrValue<string> | null,
      tradeIndex?: PromiseOrValue<BigNumberish> | null,
      disputeId?: PromiseOrValue<BytesLike> | null,
      filledAmount?: null,
      feePct?: null
    ): TradeDisputedEventFilter;
    TradeDisputed(
      relayer?: PromiseOrValue<string> | null,
      tradeIndex?: PromiseOrValue<BigNumberish> | null,
      disputeId?: PromiseOrValue<BytesLike> | null,
      filledAmount?: null,
      feePct?: null
    ): TradeDisputedEventFilter;

    "TradeFilled(address,uint256,uint256,uint256)"(
      relayer?: PromiseOrValue<string> | null,
      tradeIndex?: PromiseOrValue<BigNumberish> | null,
      feePct?: null,
      amountOut?: null
    ): TradeFilledEventFilter;
    TradeFilled(
      relayer?: PromiseOrValue<string> | null,
      tradeIndex?: PromiseOrValue<BigNumberish> | null,
      feePct?: null,
      amountOut?: null
    ): TradeFilledEventFilter;

    "TradeRequested(address,address,uint256,uint256,address,uint256)"(
      tokenIn?: PromiseOrValue<string> | null,
      tokenOut?: PromiseOrValue<string> | null,
      amountIn?: null,
      feePct?: null,
      to?: null,
      tradeIndex?: PromiseOrValue<BigNumberish> | null
    ): TradeRequestedEventFilter;
    TradeRequested(
      tokenIn?: PromiseOrValue<string> | null,
      tokenOut?: PromiseOrValue<string> | null,
      amountIn?: null,
      feePct?: null,
      to?: null,
      tradeIndex?: PromiseOrValue<BigNumberish> | null
    ): TradeRequestedEventFilter;

    "TradeSettled(address,uint256,uint256,uint256)"(
      relayer?: PromiseOrValue<string> | null,
      tradeIndex?: PromiseOrValue<BigNumberish> | null,
      filledAmount?: PromiseOrValue<BigNumberish> | null,
      feePct?: null
    ): TradeSettledEventFilter;
    TradeSettled(
      relayer?: PromiseOrValue<string> | null,
      tradeIndex?: PromiseOrValue<BigNumberish> | null,
      filledAmount?: PromiseOrValue<BigNumberish> | null,
      feePct?: null
    ): TradeSettledEventFilter;

    "UpdatedFeeForTrade(address,uint256,uint256)"(
      trader?: PromiseOrValue<string> | null,
      tradeIndex?: PromiseOrValue<BigNumberish> | null,
      newFeePct?: null
    ): UpdatedFeeForTradeEventFilter;
    UpdatedFeeForTrade(
      trader?: PromiseOrValue<string> | null,
      tradeIndex?: PromiseOrValue<BigNumberish> | null,
      newFeePct?: null
    ): UpdatedFeeForTradeEventFilter;
  };

  estimateGas: {};

  populateTransaction: {};
}
