/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BookSingleChain } from "./BookSingleChain";
export type { IBookSingleChainEvents } from "./IBookSingleChainEvents";
