/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IFloodRegistryEvents,
  IFloodRegistryEventsInterface,
} from "../../FloodRegistry.sol/IFloodRegistryEvents";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "relayer",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "whitelisted",
        type: "bool",
      },
    ],
    name: "RelayerWhitelisted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "contract IERC20",
        name: "token",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "whitelisted",
        type: "bool",
      },
    ],
    name: "TokenWhitelisted",
    type: "event",
  },
] as const;

export class IFloodRegistryEvents__factory {
  static readonly abi = _abi;
  static createInterface(): IFloodRegistryEventsInterface {
    return new utils.Interface(_abi) as IFloodRegistryEventsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IFloodRegistryEvents {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IFloodRegistryEvents;
  }
}
