/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { FloodRegistry__factory } from "./FloodRegistry__factory";
export { IFloodRegistryEvents__factory } from "./IFloodRegistryEvents__factory";
