/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FloodRegistry } from "./FloodRegistry";
export type { IFloodRegistryEvents } from "./IFloodRegistryEvents";
