/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface AllKnowingOracleInterface extends utils.Interface {
  functions: {
    "acceptOwnership()": FunctionFragment;
    "ask(address,address,address,uint256,bytes)": FunctionFragment;
    "getRequestId(address,address,address,address,uint256)": FunctionFragment;
    "owner()": FunctionFragment;
    "pendingOwner()": FunctionFragment;
    "registry()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "requests(bytes32)": FunctionFragment;
    "settle(bytes32,bool)": FunctionFragment;
    "settlers(address)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "whitelistSettler(address,bool)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "acceptOwnership"
      | "ask"
      | "getRequestId"
      | "owner"
      | "pendingOwner"
      | "registry"
      | "renounceOwnership"
      | "requests"
      | "settle"
      | "settlers"
      | "transferOwnership"
      | "whitelistSettler"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ask",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getRequestId",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingOwner",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requests",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "settle",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "settlers",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistSettler",
    values: [PromiseOrValue<string>, PromiseOrValue<boolean>]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRequestId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "requests", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "settle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "settlers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "whitelistSettler",
    data: BytesLike
  ): Result;

  events: {
    "NewRequest(bytes32,address,address,address,uint256)": EventFragment;
    "OwnershipTransferStarted(address,address)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "RequestSettled(bytes32,bool)": EventFragment;
    "RequesterWhitelisted(address,bool)": EventFragment;
    "SettlerWhitelisted(address,bool)": EventFragment;
    "TokenWhitelisted(address,bool)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "NewRequest"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferStarted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RequestSettled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RequesterWhitelisted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SettlerWhitelisted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokenWhitelisted"): EventFragment;
}

export interface NewRequestEventObject {
  id: string;
  proposer: string;
  disputer: string;
  currency: string;
  bond: BigNumber;
}
export type NewRequestEvent = TypedEvent<
  [string, string, string, string, BigNumber],
  NewRequestEventObject
>;

export type NewRequestEventFilter = TypedEventFilter<NewRequestEvent>;

export interface OwnershipTransferStartedEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferStartedEvent = TypedEvent<
  [string, string],
  OwnershipTransferStartedEventObject
>;

export type OwnershipTransferStartedEventFilter =
  TypedEventFilter<OwnershipTransferStartedEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface RequestSettledEventObject {
  id: string;
  answer: boolean;
}
export type RequestSettledEvent = TypedEvent<
  [string, boolean],
  RequestSettledEventObject
>;

export type RequestSettledEventFilter = TypedEventFilter<RequestSettledEvent>;

export interface RequesterWhitelistedEventObject {
  requester: string;
  enabled: boolean;
}
export type RequesterWhitelistedEvent = TypedEvent<
  [string, boolean],
  RequesterWhitelistedEventObject
>;

export type RequesterWhitelistedEventFilter =
  TypedEventFilter<RequesterWhitelistedEvent>;

export interface SettlerWhitelistedEventObject {
  settler: string;
  enabled: boolean;
}
export type SettlerWhitelistedEvent = TypedEvent<
  [string, boolean],
  SettlerWhitelistedEventObject
>;

export type SettlerWhitelistedEventFilter =
  TypedEventFilter<SettlerWhitelistedEvent>;

export interface TokenWhitelistedEventObject {
  token: string;
  enabled: boolean;
}
export type TokenWhitelistedEvent = TypedEvent<
  [string, boolean],
  TokenWhitelistedEventObject
>;

export type TokenWhitelistedEventFilter =
  TypedEventFilter<TokenWhitelistedEvent>;

export interface AllKnowingOracle extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: AllKnowingOracleInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    acceptOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    ask(
      proposer: PromiseOrValue<string>,
      disputer: PromiseOrValue<string>,
      currency: PromiseOrValue<string>,
      bond: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getRequestId(
      sender: PromiseOrValue<string>,
      proposer: PromiseOrValue<string>,
      disputer: PromiseOrValue<string>,
      currency: PromiseOrValue<string>,
      bond: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    pendingOwner(overrides?: CallOverrides): Promise<[string]>;

    registry(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    requests(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, string, BigNumber, number, boolean, string] & {
        requester: string;
        proposer: string;
        disputer: string;
        currency: string;
        bond: BigNumber;
        state: number;
        answer: boolean;
        data: string;
      }
    >;

    settle(
      id: PromiseOrValue<BytesLike>,
      answer: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    settlers(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    whitelistSettler(
      settler: PromiseOrValue<string>,
      enabled: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  acceptOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  ask(
    proposer: PromiseOrValue<string>,
    disputer: PromiseOrValue<string>,
    currency: PromiseOrValue<string>,
    bond: PromiseOrValue<BigNumberish>,
    data: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getRequestId(
    sender: PromiseOrValue<string>,
    proposer: PromiseOrValue<string>,
    disputer: PromiseOrValue<string>,
    currency: PromiseOrValue<string>,
    bond: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  pendingOwner(overrides?: CallOverrides): Promise<string>;

  registry(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  requests(
    arg0: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<
    [string, string, string, string, BigNumber, number, boolean, string] & {
      requester: string;
      proposer: string;
      disputer: string;
      currency: string;
      bond: BigNumber;
      state: number;
      answer: boolean;
      data: string;
    }
  >;

  settle(
    id: PromiseOrValue<BytesLike>,
    answer: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  settlers(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  whitelistSettler(
    settler: PromiseOrValue<string>,
    enabled: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    acceptOwnership(overrides?: CallOverrides): Promise<void>;

    ask(
      proposer: PromiseOrValue<string>,
      disputer: PromiseOrValue<string>,
      currency: PromiseOrValue<string>,
      bond: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    getRequestId(
      sender: PromiseOrValue<string>,
      proposer: PromiseOrValue<string>,
      disputer: PromiseOrValue<string>,
      currency: PromiseOrValue<string>,
      bond: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    pendingOwner(overrides?: CallOverrides): Promise<string>;

    registry(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    requests(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, string, BigNumber, number, boolean, string] & {
        requester: string;
        proposer: string;
        disputer: string;
        currency: string;
        bond: BigNumber;
        state: number;
        answer: boolean;
        data: string;
      }
    >;

    settle(
      id: PromiseOrValue<BytesLike>,
      answer: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    settlers(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    whitelistSettler(
      settler: PromiseOrValue<string>,
      enabled: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "NewRequest(bytes32,address,address,address,uint256)"(
      id?: PromiseOrValue<BytesLike> | null,
      proposer?: PromiseOrValue<string> | null,
      disputer?: PromiseOrValue<string> | null,
      currency?: null,
      bond?: null
    ): NewRequestEventFilter;
    NewRequest(
      id?: PromiseOrValue<BytesLike> | null,
      proposer?: PromiseOrValue<string> | null,
      disputer?: PromiseOrValue<string> | null,
      currency?: null,
      bond?: null
    ): NewRequestEventFilter;

    "OwnershipTransferStarted(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferStartedEventFilter;
    OwnershipTransferStarted(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferStartedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "RequestSettled(bytes32,bool)"(
      id?: PromiseOrValue<BytesLike> | null,
      answer?: null
    ): RequestSettledEventFilter;
    RequestSettled(
      id?: PromiseOrValue<BytesLike> | null,
      answer?: null
    ): RequestSettledEventFilter;

    "RequesterWhitelisted(address,bool)"(
      requester?: PromiseOrValue<string> | null,
      enabled?: null
    ): RequesterWhitelistedEventFilter;
    RequesterWhitelisted(
      requester?: PromiseOrValue<string> | null,
      enabled?: null
    ): RequesterWhitelistedEventFilter;

    "SettlerWhitelisted(address,bool)"(
      settler?: PromiseOrValue<string> | null,
      enabled?: null
    ): SettlerWhitelistedEventFilter;
    SettlerWhitelisted(
      settler?: PromiseOrValue<string> | null,
      enabled?: null
    ): SettlerWhitelistedEventFilter;

    "TokenWhitelisted(address,bool)"(
      token?: PromiseOrValue<string> | null,
      enabled?: null
    ): TokenWhitelistedEventFilter;
    TokenWhitelisted(
      token?: PromiseOrValue<string> | null,
      enabled?: null
    ): TokenWhitelistedEventFilter;
  };

  estimateGas: {
    acceptOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    ask(
      proposer: PromiseOrValue<string>,
      disputer: PromiseOrValue<string>,
      currency: PromiseOrValue<string>,
      bond: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getRequestId(
      sender: PromiseOrValue<string>,
      proposer: PromiseOrValue<string>,
      disputer: PromiseOrValue<string>,
      currency: PromiseOrValue<string>,
      bond: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    pendingOwner(overrides?: CallOverrides): Promise<BigNumber>;

    registry(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    requests(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    settle(
      id: PromiseOrValue<BytesLike>,
      answer: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    settlers(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    whitelistSettler(
      settler: PromiseOrValue<string>,
      enabled: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    acceptOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    ask(
      proposer: PromiseOrValue<string>,
      disputer: PromiseOrValue<string>,
      currency: PromiseOrValue<string>,
      bond: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getRequestId(
      sender: PromiseOrValue<string>,
      proposer: PromiseOrValue<string>,
      disputer: PromiseOrValue<string>,
      currency: PromiseOrValue<string>,
      bond: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pendingOwner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    registry(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    requests(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    settle(
      id: PromiseOrValue<BytesLike>,
      answer: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    settlers(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    whitelistSettler(
      settler: PromiseOrValue<string>,
      enabled: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
