/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export type RequestStruct = {
  requester: PromiseOrValue<string>;
  proposer: PromiseOrValue<string>;
  disputer: PromiseOrValue<string>;
  currency: PromiseOrValue<string>;
  bond: PromiseOrValue<BigNumberish>;
  state: PromiseOrValue<BigNumberish>;
  answer: PromiseOrValue<boolean>;
  data: PromiseOrValue<BytesLike>;
};

export type RequestStructOutput = [
  string,
  string,
  string,
  string,
  BigNumber,
  number,
  boolean,
  string
] & {
  requester: string;
  proposer: string;
  disputer: string;
  currency: string;
  bond: BigNumber;
  state: number;
  answer: boolean;
  data: string;
};

export interface BookInterface extends utils.Interface {
  functions: {
    "cancelTrade(address,address,uint256,uint256,address,uint256)": FunctionFragment;
    "disputeBondPct()": FunctionFragment;
    "disputeTrade(address,address,uint256,uint256,address,uint256,address)": FunctionFragment;
    "feePct()": FunctionFragment;
    "fillTrade(address,address,uint256,uint256,address,uint256,address,uint256,bytes)": FunctionFragment;
    "numberOfTrades()": FunctionFragment;
    "onPriceSettled(bytes32,(address,address,address,address,uint256,uint8,bool,bytes))": FunctionFragment;
    "oracle()": FunctionFragment;
    "registry()": FunctionFragment;
    "relayerRefundPct()": FunctionFragment;
    "requestTrade(address,address,uint256,uint256,address,bool)": FunctionFragment;
    "safeBlockThreshold()": FunctionFragment;
    "settleTrade(address,address,uint256,uint256,address,uint256,address)": FunctionFragment;
    "tradeRebatePct()": FunctionFragment;
    "tradesData(bytes32)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "cancelTrade"
      | "disputeBondPct"
      | "disputeTrade"
      | "feePct"
      | "fillTrade"
      | "numberOfTrades"
      | "onPriceSettled"
      | "oracle"
      | "registry"
      | "relayerRefundPct"
      | "requestTrade"
      | "safeBlockThreshold"
      | "settleTrade"
      | "tradeRebatePct"
      | "tradesData"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "cancelTrade",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "disputeBondPct",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "disputeTrade",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(functionFragment: "feePct", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "fillTrade",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "numberOfTrades",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "onPriceSettled",
    values: [PromiseOrValue<BytesLike>, RequestStruct]
  ): string;
  encodeFunctionData(functionFragment: "oracle", values?: undefined): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "relayerRefundPct",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestTrade",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<boolean>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "safeBlockThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "settleTrade",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "tradeRebatePct",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tradesData",
    values: [PromiseOrValue<BytesLike>]
  ): string;

  decodeFunctionResult(
    functionFragment: "cancelTrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disputeBondPct",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disputeTrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "feePct", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fillTrade", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "numberOfTrades",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onPriceSettled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "oracle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "relayerRefundPct",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestTrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeBlockThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settleTrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tradeRebatePct",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tradesData", data: BytesLike): Result;

  events: {
    "FeePctSet(uint256)": EventFragment;
    "ParamsCombinationSet(uint256,uint256,uint256)": EventFragment;
    "SafeBlockThresholdSet(uint256)": EventFragment;
    "TradeCancelled(uint256,bytes32,address)": EventFragment;
    "TradeDisputeSettled(address,uint256,bytes32,bool,address)": EventFragment;
    "TradeDisputed(address,uint256,bytes32,uint256,address)": EventFragment;
    "TradeFilled(address,uint256,uint256,address)": EventFragment;
    "TradeRequested(address,address,uint256,uint256,address,uint256,address,bool,bool)": EventFragment;
    "TradeSettled(address,uint256,uint256,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "FeePctSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ParamsCombinationSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SafeBlockThresholdSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TradeCancelled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TradeDisputeSettled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TradeDisputed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TradeFilled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TradeRequested"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TradeSettled"): EventFragment;
}

export interface FeePctSetEventObject {
  feePct: BigNumber;
}
export type FeePctSetEvent = TypedEvent<[BigNumber], FeePctSetEventObject>;

export type FeePctSetEventFilter = TypedEventFilter<FeePctSetEvent>;

export interface ParamsCombinationSetEventObject {
  disputeBondPct: BigNumber;
  tradeRebatePct: BigNumber;
  relayerRefundPct: BigNumber;
}
export type ParamsCombinationSetEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber],
  ParamsCombinationSetEventObject
>;

export type ParamsCombinationSetEventFilter =
  TypedEventFilter<ParamsCombinationSetEvent>;

export interface SafeBlockThresholdSetEventObject {
  newSafeBlockThreshold: BigNumber;
}
export type SafeBlockThresholdSetEvent = TypedEvent<
  [BigNumber],
  SafeBlockThresholdSetEventObject
>;

export type SafeBlockThresholdSetEventFilter =
  TypedEventFilter<SafeBlockThresholdSetEvent>;

export interface TradeCancelledEventObject {
  tradeIndex: BigNumber;
  tradeId: string;
  trader: string;
}
export type TradeCancelledEvent = TypedEvent<
  [BigNumber, string, string],
  TradeCancelledEventObject
>;

export type TradeCancelledEventFilter = TypedEventFilter<TradeCancelledEvent>;

export interface TradeDisputeSettledEventObject {
  relayer: string;
  tradeIndex: BigNumber;
  disputeId: string;
  answer: boolean;
  trader: string;
}
export type TradeDisputeSettledEvent = TypedEvent<
  [string, BigNumber, string, boolean, string],
  TradeDisputeSettledEventObject
>;

export type TradeDisputeSettledEventFilter =
  TypedEventFilter<TradeDisputeSettledEvent>;

export interface TradeDisputedEventObject {
  relayer: string;
  tradeIndex: BigNumber;
  disputeId: string;
  filledAtBlock: BigNumber;
  trader: string;
}
export type TradeDisputedEvent = TypedEvent<
  [string, BigNumber, string, BigNumber, string],
  TradeDisputedEventObject
>;

export type TradeDisputedEventFilter = TypedEventFilter<TradeDisputedEvent>;

export interface TradeFilledEventObject {
  relayer: string;
  tradeIndex: BigNumber;
  amountOut: BigNumber;
  trader: string;
}
export type TradeFilledEvent = TypedEvent<
  [string, BigNumber, BigNumber, string],
  TradeFilledEventObject
>;

export type TradeFilledEventFilter = TypedEventFilter<TradeFilledEvent>;

export interface TradeRequestedEventObject {
  tokenIn: string;
  tokenOut: string;
  amountIn: BigNumber;
  minAmountOut: BigNumber;
  recipient: string;
  tradeIndex: BigNumber;
  trader: string;
  unwrapOutput: boolean;
  wrapInput: boolean;
}
export type TradeRequestedEvent = TypedEvent<
  [
    string,
    string,
    BigNumber,
    BigNumber,
    string,
    BigNumber,
    string,
    boolean,
    boolean
  ],
  TradeRequestedEventObject
>;

export type TradeRequestedEventFilter = TypedEventFilter<TradeRequestedEvent>;

export interface TradeSettledEventObject {
  relayer: string;
  tradeIndex: BigNumber;
  filledAtBlock: BigNumber;
  trader: string;
}
export type TradeSettledEvent = TypedEvent<
  [string, BigNumber, BigNumber, string],
  TradeSettledEventObject
>;

export type TradeSettledEventFilter = TypedEventFilter<TradeSettledEvent>;

export interface Book extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: BookInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    cancelTrade(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      minAmountOut: PromiseOrValue<BigNumberish>,
      recipient: PromiseOrValue<string>,
      tradeIndex: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    disputeBondPct(overrides?: CallOverrides): Promise<[BigNumber]>;

    disputeTrade(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      minAmountOut: PromiseOrValue<BigNumberish>,
      recipient: PromiseOrValue<string>,
      tradeIndex: PromiseOrValue<BigNumberish>,
      trader: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    feePct(overrides?: CallOverrides): Promise<[BigNumber]>;

    fillTrade(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      minAmountOut: PromiseOrValue<BigNumberish>,
      recipient: PromiseOrValue<string>,
      tradeIndex: PromiseOrValue<BigNumberish>,
      trader: PromiseOrValue<string>,
      amountToSend: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    numberOfTrades(overrides?: CallOverrides): Promise<[BigNumber]>;

    onPriceSettled(
      id: PromiseOrValue<BytesLike>,
      request: RequestStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    oracle(overrides?: CallOverrides): Promise<[string]>;

    registry(overrides?: CallOverrides): Promise<[string]>;

    relayerRefundPct(overrides?: CallOverrides): Promise<[BigNumber]>;

    requestTrade(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      minAmountOut: PromiseOrValue<BigNumberish>,
      recipient: PromiseOrValue<string>,
      unwrapOutput: PromiseOrValue<boolean>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    safeBlockThreshold(overrides?: CallOverrides): Promise<[BigNumber]>;

    settleTrade(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      minAmountOut: PromiseOrValue<BigNumberish>,
      recipient: PromiseOrValue<string>,
      tradeIndex: PromiseOrValue<BigNumberish>,
      trader: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    tradeRebatePct(overrides?: CallOverrides): Promise<[BigNumber]>;

    tradesData(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, number, boolean, boolean, BigNumber] & {
        filledAtBlock: BigNumber;
        filledBy: string;
        status: number;
        unwrapOutput: boolean;
        wrapInput: boolean;
        amountPaid: BigNumber;
      }
    >;
  };

  cancelTrade(
    tokenIn: PromiseOrValue<string>,
    tokenOut: PromiseOrValue<string>,
    amountIn: PromiseOrValue<BigNumberish>,
    minAmountOut: PromiseOrValue<BigNumberish>,
    recipient: PromiseOrValue<string>,
    tradeIndex: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  disputeBondPct(overrides?: CallOverrides): Promise<BigNumber>;

  disputeTrade(
    tokenIn: PromiseOrValue<string>,
    tokenOut: PromiseOrValue<string>,
    amountIn: PromiseOrValue<BigNumberish>,
    minAmountOut: PromiseOrValue<BigNumberish>,
    recipient: PromiseOrValue<string>,
    tradeIndex: PromiseOrValue<BigNumberish>,
    trader: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  feePct(overrides?: CallOverrides): Promise<BigNumber>;

  fillTrade(
    tokenIn: PromiseOrValue<string>,
    tokenOut: PromiseOrValue<string>,
    amountIn: PromiseOrValue<BigNumberish>,
    minAmountOut: PromiseOrValue<BigNumberish>,
    recipient: PromiseOrValue<string>,
    tradeIndex: PromiseOrValue<BigNumberish>,
    trader: PromiseOrValue<string>,
    amountToSend: PromiseOrValue<BigNumberish>,
    data: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  numberOfTrades(overrides?: CallOverrides): Promise<BigNumber>;

  onPriceSettled(
    id: PromiseOrValue<BytesLike>,
    request: RequestStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  oracle(overrides?: CallOverrides): Promise<string>;

  registry(overrides?: CallOverrides): Promise<string>;

  relayerRefundPct(overrides?: CallOverrides): Promise<BigNumber>;

  requestTrade(
    tokenIn: PromiseOrValue<string>,
    tokenOut: PromiseOrValue<string>,
    amountIn: PromiseOrValue<BigNumberish>,
    minAmountOut: PromiseOrValue<BigNumberish>,
    recipient: PromiseOrValue<string>,
    unwrapOutput: PromiseOrValue<boolean>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  safeBlockThreshold(overrides?: CallOverrides): Promise<BigNumber>;

  settleTrade(
    tokenIn: PromiseOrValue<string>,
    tokenOut: PromiseOrValue<string>,
    amountIn: PromiseOrValue<BigNumberish>,
    minAmountOut: PromiseOrValue<BigNumberish>,
    recipient: PromiseOrValue<string>,
    tradeIndex: PromiseOrValue<BigNumberish>,
    trader: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  tradeRebatePct(overrides?: CallOverrides): Promise<BigNumber>;

  tradesData(
    arg0: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, string, number, boolean, boolean, BigNumber] & {
      filledAtBlock: BigNumber;
      filledBy: string;
      status: number;
      unwrapOutput: boolean;
      wrapInput: boolean;
      amountPaid: BigNumber;
    }
  >;

  callStatic: {
    cancelTrade(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      minAmountOut: PromiseOrValue<BigNumberish>,
      recipient: PromiseOrValue<string>,
      tradeIndex: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    disputeBondPct(overrides?: CallOverrides): Promise<BigNumber>;

    disputeTrade(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      minAmountOut: PromiseOrValue<BigNumberish>,
      recipient: PromiseOrValue<string>,
      tradeIndex: PromiseOrValue<BigNumberish>,
      trader: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    feePct(overrides?: CallOverrides): Promise<BigNumber>;

    fillTrade(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      minAmountOut: PromiseOrValue<BigNumberish>,
      recipient: PromiseOrValue<string>,
      tradeIndex: PromiseOrValue<BigNumberish>,
      trader: PromiseOrValue<string>,
      amountToSend: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    numberOfTrades(overrides?: CallOverrides): Promise<BigNumber>;

    onPriceSettled(
      id: PromiseOrValue<BytesLike>,
      request: RequestStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    oracle(overrides?: CallOverrides): Promise<string>;

    registry(overrides?: CallOverrides): Promise<string>;

    relayerRefundPct(overrides?: CallOverrides): Promise<BigNumber>;

    requestTrade(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      minAmountOut: PromiseOrValue<BigNumberish>,
      recipient: PromiseOrValue<string>,
      unwrapOutput: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    safeBlockThreshold(overrides?: CallOverrides): Promise<BigNumber>;

    settleTrade(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      minAmountOut: PromiseOrValue<BigNumberish>,
      recipient: PromiseOrValue<string>,
      tradeIndex: PromiseOrValue<BigNumberish>,
      trader: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    tradeRebatePct(overrides?: CallOverrides): Promise<BigNumber>;

    tradesData(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, number, boolean, boolean, BigNumber] & {
        filledAtBlock: BigNumber;
        filledBy: string;
        status: number;
        unwrapOutput: boolean;
        wrapInput: boolean;
        amountPaid: BigNumber;
      }
    >;
  };

  filters: {
    "FeePctSet(uint256)"(feePct?: null): FeePctSetEventFilter;
    FeePctSet(feePct?: null): FeePctSetEventFilter;

    "ParamsCombinationSet(uint256,uint256,uint256)"(
      disputeBondPct?: null,
      tradeRebatePct?: null,
      relayerRefundPct?: null
    ): ParamsCombinationSetEventFilter;
    ParamsCombinationSet(
      disputeBondPct?: null,
      tradeRebatePct?: null,
      relayerRefundPct?: null
    ): ParamsCombinationSetEventFilter;

    "SafeBlockThresholdSet(uint256)"(
      newSafeBlockThreshold?: null
    ): SafeBlockThresholdSetEventFilter;
    SafeBlockThresholdSet(
      newSafeBlockThreshold?: null
    ): SafeBlockThresholdSetEventFilter;

    "TradeCancelled(uint256,bytes32,address)"(
      tradeIndex?: PromiseOrValue<BigNumberish> | null,
      tradeId?: PromiseOrValue<BytesLike> | null,
      trader?: PromiseOrValue<string> | null
    ): TradeCancelledEventFilter;
    TradeCancelled(
      tradeIndex?: PromiseOrValue<BigNumberish> | null,
      tradeId?: PromiseOrValue<BytesLike> | null,
      trader?: PromiseOrValue<string> | null
    ): TradeCancelledEventFilter;

    "TradeDisputeSettled(address,uint256,bytes32,bool,address)"(
      relayer?: null,
      tradeIndex?: PromiseOrValue<BigNumberish> | null,
      disputeId?: PromiseOrValue<BytesLike> | null,
      answer?: null,
      trader?: PromiseOrValue<string> | null
    ): TradeDisputeSettledEventFilter;
    TradeDisputeSettled(
      relayer?: null,
      tradeIndex?: PromiseOrValue<BigNumberish> | null,
      disputeId?: PromiseOrValue<BytesLike> | null,
      answer?: null,
      trader?: PromiseOrValue<string> | null
    ): TradeDisputeSettledEventFilter;

    "TradeDisputed(address,uint256,bytes32,uint256,address)"(
      relayer?: null,
      tradeIndex?: PromiseOrValue<BigNumberish> | null,
      disputeId?: PromiseOrValue<BytesLike> | null,
      filledAtBlock?: null,
      trader?: PromiseOrValue<string> | null
    ): TradeDisputedEventFilter;
    TradeDisputed(
      relayer?: null,
      tradeIndex?: PromiseOrValue<BigNumberish> | null,
      disputeId?: PromiseOrValue<BytesLike> | null,
      filledAtBlock?: null,
      trader?: PromiseOrValue<string> | null
    ): TradeDisputedEventFilter;

    "TradeFilled(address,uint256,uint256,address)"(
      relayer?: PromiseOrValue<string> | null,
      tradeIndex?: PromiseOrValue<BigNumberish> | null,
      amountOut?: null,
      trader?: PromiseOrValue<string> | null
    ): TradeFilledEventFilter;
    TradeFilled(
      relayer?: PromiseOrValue<string> | null,
      tradeIndex?: PromiseOrValue<BigNumberish> | null,
      amountOut?: null,
      trader?: PromiseOrValue<string> | null
    ): TradeFilledEventFilter;

    "TradeRequested(address,address,uint256,uint256,address,uint256,address,bool,bool)"(
      tokenIn?: PromiseOrValue<string> | null,
      tokenOut?: null,
      amountIn?: null,
      minAmountOut?: null,
      recipient?: null,
      tradeIndex?: PromiseOrValue<BigNumberish> | null,
      trader?: PromiseOrValue<string> | null,
      unwrapOutput?: null,
      wrapInput?: null
    ): TradeRequestedEventFilter;
    TradeRequested(
      tokenIn?: PromiseOrValue<string> | null,
      tokenOut?: null,
      amountIn?: null,
      minAmountOut?: null,
      recipient?: null,
      tradeIndex?: PromiseOrValue<BigNumberish> | null,
      trader?: PromiseOrValue<string> | null,
      unwrapOutput?: null,
      wrapInput?: null
    ): TradeRequestedEventFilter;

    "TradeSettled(address,uint256,uint256,address)"(
      relayer?: PromiseOrValue<string> | null,
      tradeIndex?: PromiseOrValue<BigNumberish> | null,
      filledAtBlock?: null,
      trader?: PromiseOrValue<string> | null
    ): TradeSettledEventFilter;
    TradeSettled(
      relayer?: PromiseOrValue<string> | null,
      tradeIndex?: PromiseOrValue<BigNumberish> | null,
      filledAtBlock?: null,
      trader?: PromiseOrValue<string> | null
    ): TradeSettledEventFilter;
  };

  estimateGas: {
    cancelTrade(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      minAmountOut: PromiseOrValue<BigNumberish>,
      recipient: PromiseOrValue<string>,
      tradeIndex: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    disputeBondPct(overrides?: CallOverrides): Promise<BigNumber>;

    disputeTrade(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      minAmountOut: PromiseOrValue<BigNumberish>,
      recipient: PromiseOrValue<string>,
      tradeIndex: PromiseOrValue<BigNumberish>,
      trader: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    feePct(overrides?: CallOverrides): Promise<BigNumber>;

    fillTrade(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      minAmountOut: PromiseOrValue<BigNumberish>,
      recipient: PromiseOrValue<string>,
      tradeIndex: PromiseOrValue<BigNumberish>,
      trader: PromiseOrValue<string>,
      amountToSend: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    numberOfTrades(overrides?: CallOverrides): Promise<BigNumber>;

    onPriceSettled(
      id: PromiseOrValue<BytesLike>,
      request: RequestStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    oracle(overrides?: CallOverrides): Promise<BigNumber>;

    registry(overrides?: CallOverrides): Promise<BigNumber>;

    relayerRefundPct(overrides?: CallOverrides): Promise<BigNumber>;

    requestTrade(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      minAmountOut: PromiseOrValue<BigNumberish>,
      recipient: PromiseOrValue<string>,
      unwrapOutput: PromiseOrValue<boolean>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    safeBlockThreshold(overrides?: CallOverrides): Promise<BigNumber>;

    settleTrade(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      minAmountOut: PromiseOrValue<BigNumberish>,
      recipient: PromiseOrValue<string>,
      tradeIndex: PromiseOrValue<BigNumberish>,
      trader: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    tradeRebatePct(overrides?: CallOverrides): Promise<BigNumber>;

    tradesData(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    cancelTrade(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      minAmountOut: PromiseOrValue<BigNumberish>,
      recipient: PromiseOrValue<string>,
      tradeIndex: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    disputeBondPct(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    disputeTrade(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      minAmountOut: PromiseOrValue<BigNumberish>,
      recipient: PromiseOrValue<string>,
      tradeIndex: PromiseOrValue<BigNumberish>,
      trader: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    feePct(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    fillTrade(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      minAmountOut: PromiseOrValue<BigNumberish>,
      recipient: PromiseOrValue<string>,
      tradeIndex: PromiseOrValue<BigNumberish>,
      trader: PromiseOrValue<string>,
      amountToSend: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    numberOfTrades(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    onPriceSettled(
      id: PromiseOrValue<BytesLike>,
      request: RequestStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    oracle(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    registry(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    relayerRefundPct(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    requestTrade(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      minAmountOut: PromiseOrValue<BigNumberish>,
      recipient: PromiseOrValue<string>,
      unwrapOutput: PromiseOrValue<boolean>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    safeBlockThreshold(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    settleTrade(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      minAmountOut: PromiseOrValue<BigNumberish>,
      recipient: PromiseOrValue<string>,
      tradeIndex: PromiseOrValue<BigNumberish>,
      trader: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    tradeRebatePct(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    tradesData(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
