/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IFloodFillCallback } from "./IFloodFillCallback";
export type { IFloodRecipient } from "./IFloodRecipient";
